name: auth_repository
description: "A new Flutter project."
version: 0.0.1
homepage: nexus.app
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^5.1.0
  cloud_persistence:
    path: ../cloud_persistence
  domain_models:
    path: ../domain_models
  firebase_auth: ^5.1.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter: