name: whatsapp_ui
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auth:
    path: ./packages/features/auth
  cloud_firestore: ^5.1.0
  components:
    path: ./packages/ux/components
  cupertino_icons: ^1.0.2
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_database: ^11.0.3
  firebase_messaging: ^15.0.3
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  landing:
    path: ./packages/features/landing
  nav:
    path: ./packages/ux/nav

#dependency_overrides:
#  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/backgroundImage.png