name: auth
description: "A new Flutter project."
version: 0.0.1
homepage: nexus.app
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  auth_repository:
    path: ../../platform/auth_repository
  components:
    path: ../../ux/components
  country_picker: ^2.0.26
  domain_models:
    path: ../../platform/domain_models
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  image_picker: ^1.1.2
  intl: any
  nav:
    path: ../../ux/nav

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
