include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    constant_identifier_names: false
    use_setters_to_change_properties: false
    use_late_for_private_fields_and_variables: false
    no_leading_underscores_for_local_identifiers: false
