name: landing
description: "A new Flutter project."
version: 0.0.1
homepage: nexus.app
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  components:
    path: ../../ux/components
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  nav:
    path: ../../ux/nav

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  assets:
    - assets/